//
// Generated by LLVM NVPTX Back-End
//

.version 5.0
.target sm_61, texmode_independent
.address_size 64

	// .globl	square                  // -- Begin function square
                                        // @square
.entry square(
	.param .u64 .ptr .global .align 4 square_param_0,
	.param .u64 .ptr .global .align 4 square_param_1
)
{
	.reg .f32 	%f<3>;
	.reg .b32 	%r<5>;
	.reg .b64 	%rd<6>;

// %bb.0:                               // %entry
	ld.param.u64 	%rd1, [square_param_0];
	ld.param.u64 	%rd2, [square_param_1];
	mov.u32 	%r1, %ctaid.x;
	mov.u32 	%r2, %ntid.x;
	mov.u32 	%r3, %tid.x;
	mad.lo.s32 	%r4, %r2, %r1, %r3;
	mul.wide.u32 	%rd3, %r4, 4;
	add.s64 	%rd4, %rd1, %rd3;
	ld.global.f32 	%f1, [%rd4];
	mul.rn.f32 	%f2, %f1, %f1;
	add.s64 	%rd5, %rd2, %rd3;
	st.global.f32 	[%rd5], %f2;
	ret;
                                        // -- End function
}
